eureka:
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-provider
    api-b:
      path: /api-b/**
      serviceId: eureka-consumer